spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bootsprng@gmail.com
    password: qrxu maij fsea yrqs
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/balancetalk
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    data:
      host: 127.0.0.1
      port: 6379

logging.level:
  org.hibernate.SQL: debug
