package balancetalk.global.notification.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum NotificationStandard {
    FIRST_STANDARD_OF_NOTIFICATION(10),
    SECOND_STANDARD_OF_NOTIFICATION(50),
    THIRD_STANDARD_OF_NOTIFICATION(100),
    FOURTH_STANDARD_OF_NOTIFICATION(1000),
    FIRST_STANDARD_OF_VOTE_RATIO_2_1_NOTIFICATION(75),
    SECOND_STANDARD_OF_VOTE_RATIO_2_1_NOTIFICATION(150),
    THIRD_STANDARD_OF_VOTE_RATIO_2_1_NOTIFICATION(300),
    FIRST_STANDARD_OF_VOTE_RATIO_3_1_NOTIFICATION(100),
    SECOND_STANDARD_OF_VOTE_RATIO_3_1_NOTIFICATION(200),
    THIRD_STANDARD_OF_VOTE_RATIO_3_1_NOTIFICATION(300),
    FIRST_STANDARD_OF_VOTE_RATIO(2),
    SECOND_STANDARD_OF_VOTE_RATIO(3);

    private final int count;
}